(include "utils.scm")
(include "colour.scm")
(include "screen.scm")
(include "client.scm")
(include "events.scm")
(include "tile.scm")
(include "client-ops.scm")
(include "bindings.scm")
(include "main.scm")
(main)
