(include "utils.scm")
(include "colour.scm")
(include "screen.scm")
(include "manage.scm")
(include "events.scm")
(include "layouts.scm")
(include "arrange.scm")
(include "manage-ops.scm")
(include "bindings.scm")
(include "main.scm")
(main)
