#!/bin/sh

mail() {
	mails=`find -L $HOME/mail/.new -type f | wc -l`
	if [ "$mails" -gt 0 ] ; then
		echo "mail:$mails |"
	fi
}

update() {
  acpi=`acpi -b -t | awk '/^Battery 0:/ {
                                          gsub(/,/, "");
                                          bat = $3 " " $4 " " $5; 
                                        }
                          /^Thermal 0:/ {
                                          temp = $4 "°C"
                                        }
                          END {
                            print temp " | " bat
                          }'`
  vol=`amixer get Master | awk '/Mono: Playback/ {print $4}'`
  echo `mail` $vol '|' $acpi '|' `date '+%a %d %b, %H:%M'`
}

while update; do
  sleep 5
update
