(##namespace
  ("x#"
    x-client-message-event-data-l
    set-x-client-message-event-data-l!
    x-default-error-handler
    x-error-handler
    set-x-error-handler!
    x-size-hints-min-aspect-x
    x-size-hints-min-aspect-y
    x-size-hints-max-aspect-x
    x-size-hints-max-aspect-y
    x-open-display
    x-close-display
    x-grab-server
    x-ungrab-server
    x-display-width
    x-display-height
    x-default-screen
    x-screen-count
    x-screen-of-display
    x-default-colormap-of-screen
    x-clear-window
    x-connection-number
    x-root-window
    x-default-root-window
    x-root-window-of-screen
    x-default-visual
    x-default-visual-of-screen
    x-intern-atom
    x-get-atom-name
    x-default-gc
    x-default-gc-of-screen
    x-black-pixel
    x-white-pixel
    x-create-simple-window
    x-map-window
    x-kill-client
    x-flush
    x-sync
    x-grab-key
    x-ungrab-key
    x-grab-keyboard
    x-ungrab-keyboard
    x-keysym-to-keycode
    x-keycode-to-keysym
    x-keysym-to-string
    x-string-to-keysym
    x-ungrab-button
    x-grab-button
    x-create-gc
    x-fill-rectangle
    x-fill-arc
    x-draw-string
    x-text-width
    x-parse-color
    x-alloc-color
    make-x-color-box
    make-x-gc-values-box
    x-set-input-focus
    x-change-gc
    x-get-gc-values
    x-query-font
    x-load-font
    x-load-query-font
    x-font-struct-fid
    x-font-struct-ascent
    x-font-struct-descent
    x-refresh-keyboard-mapping
    x-pending
    x-check-mask-event
    x-next-event
    x-map-query-tree
    x-query-tree
    x-get-wm-protocols
    x-window-parent
    x-window-root
    x-allow-events
    x-select-input
    make-x-event-box
    x-send-event
    x-lookup-string
    x-get-window-attributes
    x-get-wm-normal-hints
    x-change-property-atoms
    set-x-window-state!
    x-set-window-border-width
    x-set-window-border
    x-reparent-window
    x-get-transient-for-hint
    x-get-text-property-list
    x-get-class-hint
    x-move-resize-window
    x-move-window
    x-resize-window
    x-raise-window
    x-configure-window
    x-change-window-attributes
    x-call-with-x11-events
    x-any-event-type
    set-x-any-event-type!
    x-any-event-serial
    set-x-any-event-serial!
    x-any-event-send-event?
    set-x-any-event-send-event!
    x-any-event-display
    set-x-any-event-display!
    x-any-event-window
    set-x-any-event-window!
    x-key-event-type
    set-x-key-event-type!
    x-key-event-serial
    set-x-key-event-serial!
    x-key-event-send-event?
    set-x-key-event-send-event!
    x-key-event-display
    set-x-key-event-display!
    x-key-event-window
    set-x-key-event-window!
    x-key-event-root
    set-x-key-event-root!
    x-key-event-subwindow
    set-x-key-event-subwindow!
    x-key-event-time
    set-x-key-event-time!
    x-key-event-x
    set-x-key-event-x!
    x-key-event-y
    set-x-key-event-y!
    x-key-event-x-root
    set-x-key-event-x-root!
    x-key-event-y-root
    set-x-key-event-y-root!
    x-key-event-state
    set-x-key-event-state!
    x-key-event-keycode
    set-x-key-event-keycode!
    x-key-event-same-screen?
    set-x-key-event-same-screen!
    x-button-event-type
    set-x-button-event-type!
    x-button-event-serial
    set-x-button-event-serial!
    x-button-event-send-event?
    set-x-button-event-send-event!
    x-button-event-display
    set-x-button-event-display!
    x-button-event-window
    set-x-button-event-window!
    x-button-event-root
    set-x-button-event-root!
    x-button-event-subwindow
    set-x-button-event-subwindow!
    x-button-event-time
    set-x-button-event-time!
    x-button-event-x
    set-x-button-event-x!
    x-button-event-y
    set-x-button-event-y!
    x-button-event-x-root
    set-x-button-event-x-root!
    x-button-event-y-root
    set-x-button-event-y-root!
    x-button-event-state
    set-x-button-event-state!
    x-button-event-button
    set-x-button-event-button!
    x-button-event-same-screen?
    set-x-button-event-same-screen!
    x-motion-event-type
    set-x-motion-event-type!
    x-motion-event-serial
    set-x-motion-event-serial!
    x-motion-event-send-event?
    set-x-motion-event-send-event!
    x-motion-event-display
    set-x-motion-event-display!
    x-motion-event-window
    set-x-motion-event-window!
    x-motion-event-root
    set-x-motion-event-root!
    x-motion-event-subwindow
    set-x-motion-event-subwindow!
    x-motion-event-time
    set-x-motion-event-time!
    x-motion-event-x
    set-x-motion-event-x!
    x-motion-event-y
    set-x-motion-event-y!
    x-motion-event-x-root
    set-x-motion-event-x-root!
    x-motion-event-y-root
    set-x-motion-event-y-root!
    x-motion-event-state
    set-x-motion-event-state!
    x-motion-event-is-hint
    set-x-motion-event-is-hint!
    x-motion-event-same-screen?
    set-x-motion-event-same-screen!
    x-crossing-event-type
    set-x-crossing-event-type!
    x-crossing-event-serial
    set-x-crossing-event-serial!
    x-crossing-event-send-event?
    set-x-crossing-event-send-event!
    x-crossing-event-display
    set-x-crossing-event-display!
    x-crossing-event-window
    set-x-crossing-event-window!
    x-crossing-event-root
    set-x-crossing-event-root!
    x-crossing-event-subwindow
    set-x-crossing-event-subwindow!
    x-crossing-event-time
    set-x-crossing-event-time!
    x-crossing-event-x
    set-x-crossing-event-x!
    x-crossing-event-y
    set-x-crossing-event-y!
    x-crossing-event-x-root
    set-x-crossing-event-x-root!
    x-crossing-event-y-root
    set-x-crossing-event-y-root!
    x-crossing-event-mode
    set-x-crossing-event-mode!
    x-crossing-event-detail
    set-x-crossing-event-detail!
    x-crossing-event-same-screen?
    set-x-crossing-event-same-screen!
    x-crossing-event-focus?
    set-x-crossing-event-focus!
    x-crossing-event-state
    set-x-crossing-event-state!
    x-focus-change-event-type
    set-x-focus-change-event-type!
    x-focus-change-event-serial
    set-x-focus-change-event-serial!
    x-focus-change-event-send-event?
    set-x-focus-change-event-send-event!
    x-focus-change-event-display
    set-x-focus-change-event-display!
    x-focus-change-event-window
    set-x-focus-change-event-window!
    x-focus-change-event-mode
    set-x-focus-change-event-mode!
    x-focus-change-event-detail
    set-x-focus-change-event-detail!
    x-keymap-event-type
    set-x-keymap-event-type!
    x-keymap-event-serial
    set-x-keymap-event-serial!
    x-keymap-event-send-event?
    set-x-keymap-event-send-event!
    x-keymap-event-display
    set-x-keymap-event-display!
    x-keymap-event-window
    set-x-keymap-event-window!
    x-expose-event-type
    set-x-expose-event-type!
    x-expose-event-serial
    set-x-expose-event-serial!
    x-expose-event-send-event?
    set-x-expose-event-send-event!
    x-expose-event-display
    set-x-expose-event-display!
    x-expose-event-window
    set-x-expose-event-window!
    x-expose-event-x
    set-x-expose-event-x!
    x-expose-event-y
    set-x-expose-event-y!
    x-expose-event-width
    set-x-expose-event-width!
    x-expose-event-height
    set-x-expose-event-height!
    x-expose-event-count
    set-x-expose-event-count!
    x-graphics-expose-event-type
    set-x-graphics-expose-event-type!
    x-graphics-expose-event-serial
    set-x-graphics-expose-event-serial!
    x-graphics-expose-event-send-event?
    set-x-graphics-expose-event-send-event!
    x-graphics-expose-event-display
    set-x-graphics-expose-event-display!
    x-graphics-expose-event-drawable
    set-x-graphics-expose-event-drawable!
    x-graphics-expose-event-x
    set-x-graphics-expose-event-x!
    x-graphics-expose-event-y
    set-x-graphics-expose-event-y!
    x-graphics-expose-event-width
    set-x-graphics-expose-event-width!
    x-graphics-expose-event-height
    set-x-graphics-expose-event-height!
    x-graphics-expose-event-count
    set-x-graphics-expose-event-count!
    x-graphics-expose-event-major-code
    set-x-graphics-expose-event-major-code!
    x-graphics-expose-event-minor-code
    set-x-graphics-expose-event-minor-code!
    x-no-expose-event-type
    set-x-no-expose-event-type!
    x-no-expose-event-serial
    set-x-no-expose-event-serial!
    x-no-expose-event-send-event?
    set-x-no-expose-event-send-event!
    x-no-expose-event-display
    set-x-no-expose-event-display!
    x-no-expose-event-drawable
    set-x-no-expose-event-drawable!
    x-no-expose-event-major-code
    set-x-no-expose-event-major-code!
    x-no-expose-event-minor-code
    set-x-no-expose-event-minor-code!
    x-visibility-event-type
    set-x-visibility-event-type!
    x-visibility-event-serial
    set-x-visibility-event-serial!
    x-visibility-event-send-event?
    set-x-visibility-event-send-event!
    x-visibility-event-display
    set-x-visibility-event-display!
    x-visibility-event-window
    set-x-visibility-event-window!
    x-visibility-event-state
    set-x-visibility-event-state!
    x-create-window-event-type
    set-x-create-window-event-type!
    x-create-window-event-serial
    set-x-create-window-event-serial!
    x-create-window-event-send-event?
    set-x-create-window-event-send-event!
    x-create-window-event-display
    set-x-create-window-event-display!
    x-create-window-event-parent
    set-x-create-window-event-parent!
    x-create-window-event-window
    set-x-create-window-event-window!
    x-create-window-event-x
    set-x-create-window-event-x!
    x-create-window-event-y
    set-x-create-window-event-y!
    x-create-window-event-width
    set-x-create-window-event-width!
    x-create-window-event-height
    set-x-create-window-event-height!
    x-create-window-event-border-width
    set-x-create-window-event-border-width!
    x-create-window-event-override-redirect?
    set-x-create-window-event-override-redirect!
    x-destroy-window-event-type
    set-x-destroy-window-event-type!
    x-destroy-window-event-serial
    set-x-destroy-window-event-serial!
    x-destroy-window-event-send-event?
    set-x-destroy-window-event-send-event!
    x-destroy-window-event-display
    set-x-destroy-window-event-display!
    x-destroy-window-event-event
    set-x-destroy-window-event-event!
    x-destroy-window-event-window
    set-x-destroy-window-event-window!
    x-unmap-event-type
    set-x-unmap-event-type!
    x-unmap-event-serial
    set-x-unmap-event-serial!
    x-unmap-event-send-event?
    set-x-unmap-event-send-event!
    x-unmap-event-display
    set-x-unmap-event-display!
    x-unmap-event-event
    set-x-unmap-event-event!
    x-unmap-event-window
    set-x-unmap-event-window!
    x-unmap-event-from-configure?
    set-x-unmap-event-from-configure!
    x-map-event-type
    set-x-map-event-type!
    x-map-event-serial
    set-x-map-event-serial!
    x-map-event-send-event?
    set-x-map-event-send-event!
    x-map-event-display
    set-x-map-event-display!
    x-map-event-event
    set-x-map-event-event!
    x-map-event-window
    set-x-map-event-window!
    x-map-event-override-redirect?
    set-x-map-event-override-redirect?!
    x-map-request-event-type
    set-x-map-request-event-type!
    x-map-request-event-serial
    set-x-map-request-event-serial!
    x-map-request-event-send-event?
    set-x-map-request-event-send-event?!
    x-map-request-event-display
    set-x-map-request-event-display!
    x-map-request-event-parent
    set-x-map-request-event-parent!
    x-map-request-event-window
    set-x-map-request-event-window!
    x-reparent-event-type
    set-x-reparent-event-type!
    x-reparent-event-serial
    set-x-reparent-event-serial!
    x-reparent-event-send-event?
    set-x-reparent-event-send-event?!
    x-reparent-event-display
    set-x-reparent-event-display!
    x-reparent-event-event
    set-x-reparent-event-event!
    x-reparent-event-window
    set-x-reparent-event-window!
    x-reparent-event-parent
    set-x-reparent-event-parent!
    x-reparent-event-x
    set-x-reparent-event-x!
    x-reparent-event-y
    set-x-reparent-event-y!
    x-reparent-event-override-redirect?
    set-x-reparent-event-override-redirect?!
    x-configure-event-type
    set-x-configure-event-type!
    x-configure-event-serial
    set-x-configure-event-serial!
    x-configure-event-send-event?
    set-x-configure-event-send-event?!
    x-configure-event-display
    set-x-configure-event-display!
    x-configure-event-event
    set-x-configure-event-event!
    x-configure-event-window
    set-x-configure-event-window!
    x-configure-event-x
    set-x-configure-event-x!
    x-configure-event-y
    set-x-configure-event-y!
    x-configure-event-width
    set-x-configure-event-width!
    x-configure-event-height
    set-x-configure-event-height!
    x-configure-event-border-width
    set-x-configure-event-border-width!
    x-configure-event-above
    set-x-configure-event-above!
    x-configure-event-override-redirect?
    set-x-configure-event-override-redirect?!
    x-gravity-event-type
    set-x-gravity-event-type!
    x-gravity-event-serial
    set-x-gravity-event-serial!
    x-gravity-event-send-event?
    set-x-gravity-event-send-event?!
    x-gravity-event-display
    set-x-gravity-event-display!
    x-gravity-event-event
    set-x-gravity-event-event!
    x-gravity-event-window
    set-x-gravity-event-window!
    x-gravity-event-x
    set-x-gravity-event-x!
    x-gravity-event-y
    set-x-gravity-event-y!
    x-resize-request-event-type
    set-x-resize-request-event-type!
    x-resize-request-event-serial
    set-x-resize-request-event-serial!
    x-resize-request-event-send-event?
    set-x-resize-request-event-send-event?!
    x-resize-request-event-display
    set-x-resize-request-event-display!
    x-resize-request-event-window
    set-x-resize-request-event-window!
    x-resize-request-event-width
    set-x-resize-request-event-width!
    x-resize-request-event-height
    set-x-resize-request-event-height!
    x-configure-request-event-type
    set-x-configure-request-event-type!
    x-configure-request-event-serial
    set-x-configure-request-event-serial!
    x-configure-request-event-send-event?
    set-x-configure-request-event-send-event?!
    x-configure-request-event-display
    set-x-configure-request-event-display!
    x-configure-request-event-parent
    set-x-configure-request-event-parent!
    x-configure-request-event-window
    set-x-configure-request-event-window!
    x-configure-request-event-x
    set-x-configure-request-event-x!
    x-configure-request-event-y
    set-x-configure-request-event-y!
    x-configure-request-event-width
    set-x-configure-request-event-width!
    x-configure-request-event-height
    set-x-configure-request-event-height!
    x-configure-request-event-border-width
    set-x-configure-request-event-border-width!
    x-configure-request-event-above
    set-x-configure-request-event-above!
    x-configure-request-event-detail
    set-x-configure-request-event-detail!
    x-configure-request-event-value-mask
    set-x-configure-request-event-value-mask!
    x-circulate-event-type
    set-x-circulate-event-type!
    x-circulate-event-serial
    set-x-circulate-event-serial!
    x-circulate-event-send-event?
    set-x-circulate-event-send-event?!
    x-circulate-event-display
    set-x-circulate-event-display!
    x-circulate-event-event
    set-x-circulate-event-event!
    x-circulate-event-window
    set-x-circulate-event-window!
    x-circulate-event-place
    set-x-circulate-event-place!
    x-circulate-request-event-type
    set-x-circulate-request-event-type!
    x-circulate-request-event-serial
    set-x-circulate-request-event-serial!
    x-circulate-request-event-send-event?
    set-x-circulate-request-event-send-event?!
    x-circulate-request-event-display
    set-x-circulate-request-event-display!
    x-circulate-request-event-parent
    set-x-circulate-request-event-parent!
    x-circulate-request-event-window
    set-x-circulate-request-event-window!
    x-circulate-request-event-place
    set-x-circulate-request-event-place!
    x-property-event-type
    set-x-property-event-type!
    x-property-event-serial
    set-x-property-event-serial!
    x-property-event-send-event?
    set-x-property-event-send-event?!
    x-property-event-display
    set-x-property-event-display!
    x-property-event-window
    set-x-property-event-window!
    x-property-event-atom
    set-x-property-event-atom!
    x-property-event-time
    set-x-property-event-time!
    x-property-event-state
    set-x-property-event-state!
    x-selection-clear-event-type
    set-x-selection-clear-event-type!
    x-selection-clear-event-serial
    set-x-selection-clear-event-serial!
    x-selection-clear-event-send-event?
    set-x-selection-clear-event-send-event?!
    x-selection-clear-event-display
    set-x-selection-clear-event-display!
    x-selection-clear-event-window
    set-x-selection-clear-event-window!
    x-selection-clear-event-selection
    set-x-selection-clear-event-selection!
    x-selection-clear-event-time
    set-x-selection-clear-event-time!
    x-selection-request-event-type
    set-x-selection-request-event-type!
    x-selection-request-event-serial
    set-x-selection-request-event-serial!
    x-selection-request-event-send-event?
    set-x-selection-request-event-send-event?!
    x-selection-request-event-display
    set-x-selection-request-event-display!
    x-selection-request-event-owner
    set-x-selection-request-event-owner!
    x-selection-request-event-requestor
    set-x-selection-request-event-requestor!
    x-selection-request-event-selection
    set-x-selection-request-event-selection!
    x-selection-request-event-target
    set-x-selection-request-event-target!
    x-selection-request-event-property
    set-x-selection-request-event-property!
    x-selection-request-event-time
    set-x-selection-request-event-time!
    x-selection-event-type
    set-x-selection-event-type!
    x-selection-event-serial
    set-x-selection-event-serial!
    x-selection-event-send-event?
    set-x-selection-event-send-event?!
    x-selection-event-display
    set-x-selection-event-display!
    x-selection-event-requestor
    set-x-selection-event-requestor!
    x-selection-event-selection
    set-x-selection-event-selection!
    x-selection-event-target
    set-x-selection-event-target!
    x-selection-event-property
    set-x-selection-event-property!
    x-selection-event-time
    set-x-selection-event-time!
    x-colormap-event-type
    set-x-colormap-event-type!
    x-colormap-event-serial
    set-x-colormap-event-serial!
    x-colormap-event-send-event?
    set-x-colormap-event-send-event?!
    x-colormap-event-display
    set-x-colormap-event-display!
    x-colormap-event-window
    set-x-colormap-event-window!
    x-colormap-event-colormap
    set-x-colormap-event-colormap!
    x-colormap-event-new?
    set-x-colormap-event-new?!
    x-colormap-event-state
    set-x-colormap-event-state!
    x-client-message-event-type
    set-x-client-message-event-type!
    x-client-message-event-serial
    set-x-client-message-event-serial!
    x-client-message-event-send-event?
    set-x-client-message-event-send-event?!
    x-client-message-event-display
    set-x-client-message-event-display!
    x-client-message-event-window
    set-x-client-message-event-window!
    x-client-message-event-message-type
    set-x-client-message-event-message-type!
    x-client-message-event-format
    set-x-client-message-event-format!
    x-mapping-event-type
    set-x-mapping-event-type!
    x-mapping-event-serial
    set-x-mapping-event-serial!
    x-mapping-event-send-event?
    set-x-mapping-event-send-event?!
    x-mapping-event-display
    set-x-mapping-event-display!
    x-mapping-event-window
    set-x-mapping-event-window!
    x-mapping-event-request
    set-x-mapping-event-request!
    x-mapping-event-first-keycode
    set-x-mapping-event-first-keycode!
    x-mapping-event-count
    set-x-mapping-event-count!
    x-error-event-type
    set-x-error-event-type!
    x-error-event-display
    set-x-error-event-display!
    x-error-event-resourceid
    set-x-error-event-resourceid!
    x-error-event-serial
    set-x-error-event-serial!
    x-error-event-error-code
    set-x-error-event-error-code!
    x-error-event-request-code
    set-x-error-event-request-code!
    x-error-event-minor-code
    set-x-error-event-minor-code!
    x-window-attributes-x
    set-x-window-attributes-x!
    x-window-attributes-y
    set-x-window-attributes-y!
    x-window-attributes-width
    set-x-window-attributes-width!
    x-window-attributes-height
    set-x-window-attributes-height!
    x-window-attributes-border-width
    set-x-window-attributes-border-width!
    x-window-attributes-depth
    set-x-window-attributes-depth!
    x-window-attributes-root
    set-x-window-attributes-root!
    x-window-attributes-class
    set-x-window-attributes-class!
    x-window-attributes-bit-gravity
    set-x-window-attributes-bit-gravity!
    x-window-attributes-win-gravity
    set-x-window-attributes-win-gravity!
    x-window-attributes-backing-store
    set-x-window-attributes-backing-store!
    x-window-attributes-backing-planes
    set-x-window-attributes-backing-planes!
    x-window-attributes-backing-pixel
    set-x-window-attributes-backing-pixel!
    x-window-attributes-save-under?
    set-x-window-attributes-save-under!
    x-window-attributes-colormap
    set-x-window-attributes-colormap!
    x-window-attributes-map-installed?
    set-x-window-attributes-map-installed!
    x-window-attributes-map-state
    set-x-window-attributes-map-state!
    x-window-attributes-all-event-masks
    set-x-window-attributes-all-event-masks!
    x-window-attributes-your-event-mask
    set-x-window-attributes-your-event-mask!
    x-window-attributes-do-not-propagate-mask
    set-x-window-attributes-do-not-propagate-mask!
    x-window-attributes-override-redirect?
    set-x-window-attributes-override-redirect!
    x-size-hints-flags
    set-x-size-hints-flags!
    x-size-hints-x
    set-x-size-hints-x!
    x-size-hints-y
    set-x-size-hints-y!
    x-size-hints-width
    set-x-size-hints-width!
    x-size-hints-height
    set-x-size-hints-height!
    x-size-hints-min-width
    set-x-size-hints-min-width!
    x-size-hints-min-height
    set-x-size-hints-min-height!
    x-size-hints-max-width
    set-x-size-hints-max-width!
    x-size-hints-max-height
    set-x-size-hints-max-height!
    x-size-hints-width-inc
    set-x-size-hints-width-inc!
    x-size-hints-height-inc
    set-x-size-hints-height-inc!
    x-size-hints-base-width
    set-x-size-hints-base-width!
    x-size-hints-base-height
    set-x-size-hints-base-height!
    x-size-hints-win-gravity
    set-x-size-hints-win-gravity!
    x-color-pixel
    set-x-color-pixel!
    x-color-red
    set-x-color-red!
    x-color-green
    set-x-color-green!
    x-color-blue
    set-x-color-blue!
    x-color-flags
    set-x-color-flags!
    x-color-pad
    set-x-color-pad!
    xgc-values-function
    set-xgc-values-function!
    xgc-values-plane-mask
    set-xgc-values-plane-mask!
    xgc-values-foreground
    set-xgc-values-foreground!
    xgc-values-background
    set-xgc-values-background!
    xgc-values-line-width
    set-xgc-values-line-width!
    xgc-values-line-style
    set-xgc-values-line-style!
    xgc-values-cap-style
    set-xgc-values-cap-style!
    xgc-values-join-style
    set-xgc-values-join-style!
    xgc-values-fill-style
    set-xgc-values-fill-style!
    xgc-values-fill-rule
    set-xgc-values-fill-rule!
    xgc-values-arc-mode
    set-xgc-values-arc-mode!
    xgc-values-tile
    set-xgc-values-tile!
    xgc-values-stipple
    set-xgc-values-stipple!
    xgc-values-ts-x-origin
    set-xgc-values-ts-x-origin!
    xgc-values-ts-y-origin
    set-xgc-values-ts-y-origin!
    xgc-values-font
    set-xgc-values-font!
    xgc-values-subwindow-mode
    set-xgc-values-subwindow-mode!
    xgc-values-graphics-exposures?
    set-xgc-values-graphics-exposures!
    xgc-values-clip-x-origin
    set-xgc-values-clip-x-origin!
    xgc-values-clip-y-origin
    set-xgc-values-clip-y-origin!
    xgc-values-clip-mask
    set-xgc-values-clip-mask!
    xgc-values-dash-offset
    set-xgc-values-dash-offset!
    xgc-values-dashes
    set-xgc-values-dashes!
    +no-value+
    +x-value+
    +y-value+
    +width-value+
    +height-value+
    +all-values+
    +x-negative+
    +y-negative+
    +us-position+
    +us-size+
    +p-position+
    +p-size+
    +p-min-size+
    +p-max-size+
    +p-resize-inc+
    +p-aspect+
    +p-base-size+
    +p-win-gravity+
    +p-all-hints+
    +input-hint+
    +state-hint+
    +icon-pixmap-hint+
    +icon-window-hint+
    +icon-position-hint+
    +icon-mask-hint+
    +window-group-hint+
    +all-hints+
    +x-urgency-hint+
    +withdrawn-state+
    +normal-state+
    +iconic-state+
    +dont-care-state+
    +zoom-state+
    +inactive-state+
    +x-no-memory+
    +x-locale-not-supported+
    +x-converter-not-found+
    +rectangle-out+
    +rectangle-in+
    +rectangle-part+
    +visual-no-mask+
    +visualid-mask+
    +visual-screen-mask+
    +visual-depth-mask+
    +visual-class-mask+
    +visual-red-mask-mask+
    +visual-green-mask-mask+
    +visual-blue-mask-mask+
    +visual-colormap-size-mask+
    +visual-bits-perrgb-mask+
    +visual-all-mask+
    +release-by-freeing-colormap+
    +bitmap-success+
    +bitmap-open-failed+
    +bitmap-file-invalid+
    +bitmap-no-memory+
    +xcsuccess+
    +xcnomem+
    +xcnoent+
    +xatom-h+
    +xa-primary+
    +xa-secondary+
    +xa-arc+
    +xa-atom+
    +xa-bitmap+
    +xa-cardinal+
    +xa-colormap+
    +xa-cursor+
    +xa-cut-buffer0+
    +xa-cut-buffer1+
    +xa-cut-buffer2+
    +xa-cut-buffer3+
    +xa-cut-buffer4+
    +xa-cut-buffer5+
    +xa-cut-buffer6+
    +xa-cut-buffer7+
    +xa-drawable+
    +xa-font+
    +xa-integer+
    +xa-pixmap+
    +xa-point+
    +xa-rectangle+
    +xa-resource-manager+
    +xa-rgb-color-map+
    +xa-rgb-best-map+
    +xa-rgb-blue-map+
    +xa-rgb-default-map+
    +xa-rgb-gray-map+
    +xa-rgb-green-map+
    +xa-rgb-red-map+
    +xa-string+
    +xa-visualid+
    +xa-window+
    +xa-wm-command+
    +xa-wm-hints+
    +xa-wm-client-machine+
    +xa-wm-icon-name+
    +xa-wm-icon-size+
    +xa-wm-name+
    +xa-wm-normal-hints+
    +xa-wm-size-hints+
    +xa-wm-zoom-hints+
    +xa-min-space+
    +xa-norm-space+
    +xa-max-space+
    +xa-end-space+
    +xa-superscript-x+
    +xa-superscript-y+
    +xa-subscript-x+
    +xa-subscript-y+
    +xa-underline-position+
    +xa-underline-thickness+
    +xa-strikeout-ascent+
    +xa-strikeout-descent+
    +xa-italic-angle+
    +xa-x-height+
    +xa-quad-width+
    +xa-weight+
    +xa-point-size+
    +xa-resolution+
    +xa-copyright+
    +xa-notice+
    +xa-font-name+
    +xa-family-name+
    +xa-full-name+
    +xa-cap-height+
    +xa-wm-class+
    +xa-wm-transient-for+
    +xa-last-predefined+
    +x-protocol+
    +x-protocol-revision+
    +none+
    +parent-relative+
    +copy-from-parent+
    +pointer-window+
    +input-focus+
    +pointer-root+
    +any-property-type+
    +any-key+
    +any-button+
    +all-temporary+
    +current-time+
    +no-symbol+
    +no-event-mask+
    +key-press-mask+
    +key-release-mask+
    +button-press-mask+
    +button-release-mask+
    +enter-window-mask+
    +leave-window-mask+
    +pointer-motion-mask+
    +pointer-motion-hint-mask+
    +button1-motion-mask+
    +button2-motion-mask+
    +button3-motion-mask+
    +button4-motion-mask+
    +button5-motion-mask+
    +button-motion-mask+
    +keymap-state-mask+
    +exposure-mask+
    +visibility-change-mask+
    +structure-notify-mask+
    +resize-redirect-mask+
    +substructure-notify-mask+
    +substructure-redirect-mask+
    +focus-change-mask+
    +property-change-mask+
    +colormap-change-mask+
    +owner-grab-button-mask+
    +key-press+
    +key-release+
    +button-press+
    +button-release+
    +motion-notify+
    +enter-notify+
    +leave-notify+
    +focus-in+
    +focus-out+
    +keymap-notify+
    +expose+
    +graphics-expose+
    +no-expose+
    +visibility-notify+
    +create-notify+
    +destroy-notify+
    +unmap-notify+
    +map-notify+
    +map-request+
    +reparent-notify+
    +configure-notify+
    +configure-request+
    +gravity-notify+
    +resize-request+
    +circulate-notify+
    +circulate-request+
    +property-notify+
    +selection-clear+
    +selection-request+
    +selection-notify+
    +colormap-notify+
    +client-message+
    +mapping-notify+
    +generic-event+
    +last-event+
    +shift-mask+
    +lock-mask+
    +control-mask+
    +mod1-mask+
    +mod2-mask+
    +mod3-mask+
    +mod4-mask+
    +mod5-mask+
    +shift-map-index+
    +lock-map-index+
    +control-map-index+
    +mod1-map-index+
    +mod2-map-index+
    +mod3-map-index+
    +mod4-map-index+
    +mod5-map-index+
    +button1-mask+
    +button2-mask+
    +button3-mask+
    +button4-mask+
    +button5-mask+
    +any-modifier+
    +button1+
    +button2+
    +button3+
    +button4+
    +button5+
    +notify-normal+
    +notify-grab+
    +notify-ungrab+
    +notify-while-grabbed+
    +notify-hint+
    +notify-ancestor+
    +notify-virtual+
    +notify-inferior+
    +notify-nonlinear+
    +notify-nonlinear-virtual+
    +notify-pointer+
    +notify-pointer-root+
    +notify-detail-none+
    +visibility-unobscured+
    +visibility-partially-obscured+
    +visibility-fully-obscured+
    +place-on-top+
    +place-on-bottom+
    +family-internet+
    +familyde-cnet+
    +family-chaos+
    +family-internet6+
    +family-server-interpreted+
    +property-new-value+
    +property-delete+
    +colormap-uninstalled+
    +colormap-installed+
    +grab-mode-sync+
    +grab-mode-async+
    +grab-success+
    +already-grabbed+
    +grab-invalid-time+
    +grab-not-viewable+
    +grab-frozen+
    +async-pointer+
    +sync-pointer+
    +replay-pointer+
    +async-keyboard+
    +sync-keyboard+
    +replay-keyboard+
    +async-both+
    +sync-both+
    +revert-to-none+
    +revert-to-pointer-root+
    +revert-to-parent+
    +success+
    +bad-request+
    +bad-value+
    +bad-window+
    +bad-pixmap+
    +bad-atom+
    +bad-cursor+
    +bad-font+
    +bad-match+
    +bad-drawable+
    +bad-access+
    +bad-alloc+
    +bad-color+
    +badgc+
    +badid-choice+
    +bad-name+
    +bad-length+
    +bad-implementation+
    +first-extension-error+
    +last-extension-error+
    +input-output+
    +input-only+
    +cw-back-pixmap+
    +cw-back-pixel+
    +cw-border-pixmap+
    +cw-border-pixel+
    +cw-bit-gravity+
    +cw-win-gravity+
    +cw-backing-store+
    +cw-backing-planes+
    +cw-backing-pixel+
    +cw-override-redirect+
    +cw-save-under+
    +cw-event-mask+
    +cw-dont-propagate+
    +cw-colormap+
    +cw-cursor+
    +cwx+
    +cwy+
    +cw-width+
    +cw-height+
    +cw-border-width+
    +cw-sibling+
    +cw-stack-mode+
    +forget-gravity+
    +north-west-gravity+
    +north-gravity+
    +north-east-gravity+
    +west-gravity+
    +center-gravity+
    +east-gravity+
    +south-west-gravity+
    +south-gravity+
    +south-east-gravity+
    +static-gravity+
    +unmap-gravity+
    +not-useful+
    +when-mapped+
    +always+
    +is-unmapped+
    +is-unviewable+
    +is-viewable+
    +set-mode-insert+
    +set-mode-delete+
    +destroy-all+
    +retain-permanent+
    +retain-temporary+
    +above+
    +below+
    +top-if+
    +bottom-if+
    +opposite+
    +raise-lowest+
    +lower-highest+
    +prop-mode-replace+
    +prop-mode-prepend+
    +prop-mode-append+
    +g-xclear+
    +g-xand+
    +g-xand-reverse+
    +g-xcopy+
    +g-xand-inverted+
    +g-xnoop+
    +g-xxor+
    +g-xor+
    +g-xnor+
    +g-xequiv+
    +g-xinvert+
    +g-xor-reverse+
    +g-xcopy-inverted+
    +g-xor-inverted+
    +g-xnand+
    +g-xset+
    +line-solid+
    +line-on-off-dash+
    +line-double-dash+
    +cap-not-last+
    +cap-butt+
    +cap-round+
    +cap-projecting+
    +join-miter+
    +join-round+
    +join-bevel+
    +fill-solid+
    +fill-tiled+
    +fill-stippled+
    +fill-opaque-stippled+
    +even-odd-rule+
    +winding-rule+
    +clip-by-children+
    +include-inferiors+
    +unsorted+
    +y-sorted+
    +yx-sorted+
    +yx-banded+
    +coord-mode-origin+
    +coord-mode-previous+
    +complex+
    +nonconvex+
    +convex+
    +arc-chord+
    +arc-pie-slice+
    +gc-function+
    +gc-plane-mask+
    +gc-foreground+
    +gc-background+
    +gc-line-width+
    +gc-line-style+
    +gc-cap-style+
    +gc-join-style+
    +gc-fill-style+
    +gc-fill-rule+
    +gc-tile+
    +gc-stipple+
    +gc-tile-stipx-origin+
    +gc-tile-stipy-origin+
    +gc-font+
    +gc-subwindow-mode+
    +gc-graphics-exposures+
    +gc-clipx-origin+
    +gc-clipy-origin+
    +gc-clip-mask+
    +gc-dash-offset+
    +gc-dash-list+
    +gc-arc-mode+
    +gc-last-bit+
    +font-left-to-right+
    +font-right-to-left+
    +font-change+
    +xy-bitmap+
    +xy-pixmap+
    +z-pixmap+
    +alloc-none+
    +alloc-all+
    +do-red+
    +do-green+
    +do-blue+
    +cursor-shape+
    +tile-shape+
    +stipple-shape+
    +auto-repeat-mode-off+
    +auto-repeat-mode-on+
    +auto-repeat-mode-default+
    +led-mode-off+
    +led-mode-on+
    +kb-key-click-percent+
    +kb-bell-percent+
    +kb-bell-pitch+
    +kb-bell-duration+
    +kb-led+
    +kb-led-mode+
    +kb-key+
    +kb-auto-repeat-mode+
    +mapping-success+
    +mapping-busy+
    +mapping-failed+
    +mapping-modifier+
    +mapping-keyboard+
    +mapping-pointer+
    +dont-prefer-blanking+
    +prefer-blanking+
    +default-blanking+
    +disable-screen-saver+
    +disable-screen-interval+
    +dont-allow-exposures+
    +allow-exposures+
    +default-exposures+
    +screen-saver-reset+
    +screen-saver-active+
    +host-insert+
    +host-delete+
    +enable-access+
    +disable-access+
    +static-gray+
    +gray-scale+
    +static-color+
    +pseudo-color+
    +true-color+
    +direct-color+
    +lsb-first+
    +msb-first+
    +x-tcp-port+
    +el-flag-focus+
    +el-flag-same-screen+
    +x-event-size+
    +x-reply+
    +x-error+
    +x-create-window+
    +x-change-window-attributes+
    +x-get-window-attributes+
    +x-destroy-window+
    +x-destroy-subwindows+
    +x-change-save-set+
    +x-reparent-window+
    +x-map-window+
    +x-map-subwindows+
    +x-unmap-window+
    +x-unmap-subwindows+
    +x-configure-window+
    +x-circulate-window+
    +x-get-geometry+
    +x-query-tree+
    +x-intern-atom+
    +x-get-atom-name+
    +x-change-property+
    +x-delete-property+
    +x-get-property+
    +x-list-properties+
    +x-set-selection-owner+
    +x-get-selection-owner+
    +x-convert-selection+
    +x-send-event+
    +x-grab-pointer+
    +x-ungrab-pointer+
    +x-grab-button+
    +x-ungrab-button+
    +x-change-active-pointer-grab+
    +x-grab-keyboard+
    +x-ungrab-keyboard+
    +x-grab-key+
    +x-ungrab-key+
    +x-allow-events+
    +x-grab-server+
    +x-ungrab-server+
    +x-query-pointer+
    +x-get-motion-events+
    +x-translate-coords+
    +x-warp-pointer+
    +x-set-input-focus+
    +x-get-input-focus+
    +x-query-keymap+
    +x-open-font+
    +x-close-font+
    +x-query-font+
    +x-query-text-extents+
    +x-list-fonts+
    +x-list-fonts-with-info+
    +x-set-font-path+
    +x-get-font-path+
    +x-create-pixmap+
    +x-free-pixmap+
    +x-creategc+
    +x-changegc+
    +x-copygc+
    +x-set-dashes+
    +x-set-clip-rectangles+
    +x-freegc+
    +x-clear-area+
    +x-copy-area+
    +x-copy-plane+
    +x-poly-point+
    +x-poly-line+
    +x-poly-segment+
    +x-poly-rectangle+
    +x-poly-arc+
    +x-fill-poly+
    +x-poly-fill-rectangle+
    +x-poly-fill-arc+
    +x-put-image+
    +x-get-image+
    +x-poly-text8+
    +x-poly-text16+
    +x-image-text8+
    +x-image-text16+
    +x-create-colormap+
    +x-free-colormap+
    +x-copy-colormap-and-free+
    +x-install-colormap+
    +x-uninstall-colormap+
    +x-list-installed-colormaps+
    +x-alloc-color+
    +x-alloc-named-color+
    +x-alloc-color-cells+
    +x-alloc-color-planes+
    +x-free-colors+
    +x-store-colors+
    +x-store-named-color+
    +x-query-colors+
    +x-lookup-color+
    +x-create-cursor+
    +x-create-glyph-cursor+
    +x-free-cursor+
    +x-recolor-cursor+
    +x-query-best-size+
    +x-query-extension+
    +x-list-extensions+
    +x-change-keyboard-mapping+
    +x-get-keyboard-mapping+
    +x-change-keyboard-control+
    +x-get-keyboard-control+
    +x-bell+
    +x-change-pointer-control+
    +x-get-pointer-control+
    +x-set-screen-saver+
    +x-get-screen-saver+
    +x-change-hosts+
    +x-list-hosts+
    +x-set-access-control+
    +x-set-close-down-mode+
    +x-kill-client+
    +x-rotate-properties+
    +x-force-screen-saver+
    +x-set-pointer-mapping+
    +x-get-pointer-mapping+
    +x-set-modifier-mapping+
    +x-get-modifier-mapping+
    +x-no-operation+))
