(define-c-struct ("XGCValues")
  (int function)
  (unsigned-long plane_mask)
  (unsigned-long foreground)
  (unsigned-long background)
  (int line_width)
  (int line_style)
  (int cap_style)
  (int join_style)
  (int fill_style)
  (int fill_rule)
  (int arc_mode)
  (Pixmap tile)
  (Pixmap stipple)
  (int ts_x_origin)
  (int ts_y_origin)
  (Font font)
  (int subwindow_mode)
  (Bool graphics_exposures)
  (int clip_x_origin)
  (int clip_y_origin)
  (Pixmap clip_mask)
  (int dash_offset)
  (char dashes))

(define-c-struct ("XWindowAttributes")
  (int x)
  (int y)
  (int width)
  (int height)
  (int border_width)
  (int depth)
  (Visual* visual)
  (Window root)
  (int class)
  (int bit_gravity)
  (int win_gravity)
  (int backing_store)
  (unsigned-long backing_planes)
  (unsigned-long backing_pixel)
  (Bool save_under)
  (Colormap colormap)
  (Bool map_installed)
  (int map_state)
  (long all_event_masks)
  (long your_event_mask)
  (long do_not_propagate_mask)
  (Bool override_redirect)
  (Screen* screen))

(define-c-struct ("XColor")
  (unsigned-long pixel)
  (unsigned-short red)
  (unsigned-short green)
  (unsigned-short blue)
  (char flags)
  (char pad))

(define-c-struct ("XKeyEvent" "xkey")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (Window root)
  (Window subwindow)
  (Time time)
  (int x)
  (int y)
  (int x_root)
  (int y_root)
  (unsigned-int state)
  (unsigned-int keycode)
  (Bool same_screen))

(define-c-struct ("XButtonEvent" "xbutton")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (Window root)
  (Window subwindow)
  (Time time)
  (int x)
  (int y)
  (int x_root)
  (int y_root)
  (unsigned-int state)
  (unsigned-int button)
  (Bool same_screen))

(define-c-struct ("XMotionEvent" "xmotion")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (Window root)
  (Window subwindow)
  (Time time)
  (int x)
  (int y)
  (int x_root)
  (int y_root)
  (unsigned-int state)
  (char is_hint)
  (Bool same_screen))

(define-c-struct ("XCrossingEvent" "xcrossing")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (Window root)
  (Window subwindow)
  (Time time)
  (int x)
  (int y)
  (int x_root)
  (int y_root)
  (int mode)
  (int detail)
  (Bool same_screen)
  (Bool focus)
  (unsigned-int state))

(define-c-struct ("XFocusChangeEvent" "xfocus")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (int mode)
  (int detail))

(define-c-struct ("XKeymapEvent" "xkeymap")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window))

(define-c-struct ("XExposeEvent" "xexpose")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (int x)
  (int y)
  (int width)
  (int height)
  (int count))

(define-c-struct ("XGraphicsExposeEvent" "xgraphicsexpose")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Drawable drawable)
  (int x)
  (int y)
  (int width)
  (int height)
  (int count)
  (int major_code)
  (int minor_code))

(define-c-struct ("XNoExposeEvent" "xnoexpose")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Drawable drawable)
  (int major_code)
  (int minor_code))

(define-c-struct ("XVisibilityEvent" "xvisibility")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (int state))

(define-c-struct ("XCreateWindowEvent" "xcreatewindow")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window parent)
  (Window window)
  (int x)
  (int y)
  (int width)
  (int height)
  (int border_width)
  (Bool override_redirect))

(define-c-struct ("XDestroyWindowEvent" "xdestroywindow")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window event)
  (Window window))

(define-c-struct ("XUnmapEvent" "xunmap")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window event)
  (Window window)
  (Bool from_configure))

(define-c-struct ("XMapEvent" "xmap")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window event)
  (Window window)
  (Bool override_redirect))

(define-c-struct ("XMapRequestEvent" "xmaprequest")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window parent)
  (Window window))

(define-c-struct ("XReparentEvent" "xreparent")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window event)
  (Window window)
  (Window parent)
  (int x)
  (int y)
  (Bool override_redirect))

(define-c-struct ("XConfigureEvent" "xconfigure")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window event)
  (Window window)
  (int x)
  (int y)
  (int width)
  (int height)
  (int border_width)
  (Window above)
  (Bool override_redirect))

(define-c-struct ("XGravityEvent" "xgravity")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window event)
  (Window window)
  (int x)
  (int y))

(define-c-struct ("XResizeRequestEvent" "xresizerequest")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (int width)
  (int height))

(define-c-struct ("XConfigureRequestEvent" "xconfigurerequest")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window parent)
  (Window window)
  (int x)
  (int y)
  (int width)
  (int height)
  (int border_width)
  (Window above)
  (int detail)
  (unsigned-long value_mask))

(define-c-struct ("XCirculateEvent" "xcirculate")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window event)
  (Window window)
  (int place))

(define-c-struct ("XCirculateRequestEvent" "xcirculaterequest")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window parent)
  (Window window)
  (int place))

(define-c-struct ("XPropertyEvent" "xproperty")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (Atom atom)
  (Time time)
  (int state))

(define-c-struct ("XSelectionClearEvent" "xselectionclear")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (Atom selection)
  (Time time))

(define-c-struct ("XSelectionRequestEvent" "xselectionrequest")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window owner)
  (Window requestor)
  (Atom selection)
  (Atom target)
  (Atom property)
  (Time time))

(define-c-struct ("XSelectionEvent" "xselection")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window requestor)
  (Atom selection)
  (Atom target)
  (Atom property)
  (Time time))

(define-c-struct ("XColormapEvent" "xcolormap")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (Colormap colormap)
  (Bool new)
  (int state))

(define-c-struct ("XClientMessageEvent" "xclient")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (Atom message_type)
  (int format))

(define-c-struct ("XMappingEvent" "xmapping")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window)
  (int request)
  (int first_keycode)
  (int count))

(define-c-struct ("XErrorEvent" "xerror")
  (int type)
  (Display* display)
  (XID resourceid)
  (unsigned-long serial)
  (unsigned-char error_code)
  (unsigned-char request_code)
  (unsigned-char minor_code))

(define-c-struct ("XAnyEvent" "xany")
  (int type)
  (unsigned-long serial)
  (Bool send_event)
  (Display* display)
  (Window window))

(define-c-struct ("XSizeHints")
  (long flags)
  (int x)
  (int y)
  (int width)
  (int height)
  (int min_width)
  (int min_height)
  (int max_width)
  (int max_height)
  (int width_inc)
  (int height_inc)
  (int base_width)
  (int base_height)
  (int win_gravity))

